she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newsStory'),
    path('story/<int:pk>/edit', views.EditStoryView.as_view(), name='editStory'),
    path('story/<int:pk>/delete', views.DeleteStoryView.as_view(), name='deleteStory')
    ]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, CreateUserProfileView, YourProfile

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('create-profile/', CreateUserProfileView.as_view(), name='createProfile'),
    path('<int:pk>', YourProfile.as_view(), name='yourprofile'),
    # path('authors/', AuthorsView.as_view(), name='authors'),
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models

# class Category(models.Model):
#     name = models

class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    # author = models.CharField(max_length=200)
    author=models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    
    pub_date = models.DateTimeField()
    image = models.URLField(blank=True) 
    content = models.TextField()
    # category = models.CharField(max_length=225,)
    
    class Meta: 
        ordering = ['-pub_date']

she_codes_news/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models



class CustomUser(AbstractUser):
    avatar = models.URLField(blank=True)
    socials = models.URLField(blank=True)
    location = models.CharField(max_length=50, blank=True)
    about = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from.models import NewsStory
from django.utils import timezone

class StoryForm(forms.ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'image', 'pub_date', 'content']
        # widgets = {
        # 'pub_date': forms.DateInput(format=('%m/%d/%y'), attrs={'class':'form-control', 'placeholder':'select a date', 'type':'date'}),
        # }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['pub_date'].initial = timezone.now().strftime("%Y-%m-%dT%H:%M")
        

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta: 
        model = CustomUser
        fields = ['first_name', 'last_name','username', 'email', 'password1', 'password2']

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']

class CreateUserProfileForm(forms.ModelForm):
    avatar = forms.URLField(required=False)
    socials = forms.URLField(required=False)
    location = forms.CharField(max_length=50, required=False, help_text='Where are you writing from?')
    about = forms.CharField(widget=forms.Textarea, max_length=500, required=False, help_text='Tell us about yourself :-)')

    class Meta:
        model = CustomUser
        fields = ['avatar', 'socials', 'location', 'about']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm
from django.views.generic.edit import DeleteView, UpdateView


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all().order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.all().order_by('-pub_date')
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class EditStoryView(UpdateView):
    model = NewsStory
    template = 'news/newsstory_form.html'
    fields = ['title', 'image', 'pub_date', 'content']
    success_url = reverse_lazy('news:index')

class DeleteStoryView(DeleteView):
    model = NewsStory
    success_url = reverse_lazy('news:index')
    
    # def form_valid(self, form):
    #     form.instance.author = self.request.user
    #     return super().form_valid(form)

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, FormView, UpdateView, DeleteView
from django.views import generic 
from .models import CustomUser
from .forms import CustomUserCreationForm, CreateUserProfileForm
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import login
from django.views.generic import DetailView, ListView
from news.models import NewsStory


class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:createProfile')
    template_name = 'users/createAccount.html'

    def form_valid(self, form):
        f=super().form_valid(form)
        user = self.object
        login(self.request, user)
        return f

class CreateUserProfileView(UpdateView):
    form_class = CreateUserProfileForm
    success_url = reverse_lazy('users:homePage')
    template_name = 'users/userProfileForm.html'
    
    def get_success_url(self):
        print(self.request.user.id)
        print(type(self.get_form()))
        return reverse_lazy('users:yourprofile', kwargs={"pk":self.request.user.id})

    def get_object(self):
        return self.request.user

class YourProfile(generic.DetailView):
    model = CustomUser
    template_name = 'users/yourprofile.html'







    

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %} 

{% block content %} 

<form action="" method="post">
    {% csrf_token %} 
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>

{% endblock %} 

she_codes_news/news/templates/news/index.html
    {% extends "base.html" %}
    {% load static %} 
    
    {% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
    {% endblock %}

    {% block content %} 

    <h2>Latest News</h2>

    <div id="Write New Story">
    {% if request.user.is_authenticated %} 
    <a href="{% url 'news:newsStory' %}"><h2>Write New Story</h2></a>
    {% else %}
    {% endif %}
    </div>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    
    {% comment %} <div id="View By Author">
    <a href="{% url 'users:authors' %}"><h2>View By Author</h2></a>
    </div> {% endcomment %}

    {% endblock %}

she_codes_news/news/templates/news/newsstory_confirm_delete.html
{% extends "base.html" %}
{% load static %} 

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} 

{% block content %}
<h3>Are you sure you want to delete "{{ newsstory.title }}"?</h3>
<br/>
<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary">Delete</button>
    </div>

{% endblock %} 

she_codes_news/news/templates/news/newsstory_form.html
{% extends "base.html" %}
{% load static %} 

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} 

{% block content %}

<div id="edit-wrapper">
<h3>Edit your story "{{ newsstory.title }}"</h3>
<br/>
<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary">Edit Story</button>
    </div>

{% endblock %} 

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %} 

{% block stylesheets %} 
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %} 

{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4> 
        <a href="{% url 'users:yourprofile' story.author.id %}">
        {{ story.author }}
        </a>
    </h4>
    <div id="story-content">
        {% if story.image %}
            <img src="{{ story.image }}" alt="image">
        {% else %}
            <img src="{% static '/news/images/placeholder-5.jpg' %}">
        {{ story.content|linebreaks }}
        {% endif %}
    </div>
    
{% if request.user == story.author %}
    <a href="{% url 'news:editStory' story.id %}">Edit Story</a> <br/>
    <a href="{% url 'news:deleteStory' story.id %}">Delete</a> <br/>
{% else %}
{% endif %}
</div>
{% endblock %} 

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">

        {% if story.image %}
            <img src="{{story.image}}">
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}
        <div class="story-card-text">
            <a href="{% url 'news:story' story.id %}"><h3>{{ story.title }}</h3></a>
            <a href="{% url 'users:yourprofile' story.author.id %}">{{ story.author }}</a>
            <h4>{{ story.pub_date|date:'r' }}</h4>
        </div>
    
</div>

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Khia Emslie-O'Brien">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        {% block content %}{% endblock %}
        
    </body>
</html>

she_codes_news/templates/django/forms/widgets/datetime.html
<input 
  type="datetime-local"
  name="{{ widget.name }}"
  {% if widget.value != None %}
    value="{{ widget.value|stringformat:'s' }}"
  {% endif %}
  {% include "django/forms/widgets/attrs.html" %}
>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %} 
    <a href="{% url 'users:yourprofile' request.user.id %}">{{ request.user.username }}</a>
    <a href="{% url 'logout' %}">Logout</a>
    
    {% else %}
    <a href="{% url 'users:createAccount' %}">Create Account</a>
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
</nav>



   

she_codes_news/users/templates/users/authors.html
{% extends 'base.html' %} 
{% load static %}

{% block content %} 
<h2>Authors</h2>

    <div>
        {% for author in authors %}
            {% include "./yourprofile.html" with author=author position=forloop.counter %}
            {% endfor %}
            {{ author.name }}
        
    </div>

{% endblock %} 

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %} 

{% block content %} 
<h2>Create Account</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %} 

she_codes_news/users/templates/users/homePageView.html
{% extends 'base.html' %} 
{% load static %}

{% block content %} 
<h2>My Profile</h2>
{{customuser.username}}


<div id="stories">
    {% if customuser.newsstory_set.all %}
        {% for story in customuser.newsstory_set.all %}
            {% include "news/storyCard.html" with story=story position=forloop.counter %}
        {% endfor %}
    {% else %}
        <p>No stories are available.</p>
    {% endif %}
</div>

{% endblock %} 

she_codes_news/users/templates/users/userProfileForm.html
{% extends 'base.html' %} 

{% block content %} 
<h2>Create Profile</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Create Profile</button>
    <button type="skip">I'll do this later</button>
  </form>
{% endblock %} 

she_codes_news/users/templates/users/userProfileForm1.html
{% extends 'base.html' %} 

{% block content %} 
<h2>Create Profile</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Create Profile</button>
    <button type="skip">I'll do this later</button>
  </form>
{% endblock %} 

she_codes_news/users/templates/users/userprofileform.html
{% extends 'base.html' %} 

{% block content %} 
<h2>Create Profile</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Create Profile</button>
    <button type="skip">I'll do this later</button>
  </form>
{% endblock %} 

she_codes_news/users/templates/users/yourprofile.html
{% extends 'base.html' %} 
{% load static %}

{% block content %} 
<h2>My Profile</h2>
<h3>{{customuser.username}}</h3>

<div id="profile-wrapper">
    <h4> 
        <img src="{{ customuser.avatar }}" alt="avatar"> <br>
        {{ customuser.location }} <br> 
        {{ customuser.about }} <br>
        {% if request.user == customuser %}
  <button><a href="{% url 'users:createProfile' %}">Edit Your Profile</a></button>
{% else %}
{% endif %}
    </h4>
</div>

<h2>Your Stories</h2>
 
<div id="stories">
    <div id="Write New Story">
        <a href="{% url 'news:newsStory' %}"><h2>Write New Story</h2></a>
    </div>
    {% if customuser.newsstory_set.all %}
        {% for story in customuser.newsstory_set.all %}
            {% include "news/storyCard.html" with story=story position=forloop.counter %}
        {% endfor %}
    {% else %}
        <p>No stories are available.</p>
    {% endif %}
</div>

{% endblock %} 